// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydzYSDSQvrlTGwfmXtKiEazzw_apyuaE',
    appId: '1:311227783889:android:2ea23e0746211b948583f0',
    messagingSenderId: '311227783889',
    projectId: 'kazipur-shop-sk',
    databaseURL: 'https://kazipur-shop-sk-default-rtdb.firebaseio.com',
    storageBucket: 'kazipur-shop-sk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumWPgB5TxlBD-L-MIePCIfM9fDCyALd4',
    appId: '1:311227783889:ios:a2a10fce7dc455658583f0',
    messagingSenderId: '311227783889',
    projectId: 'kazipur-shop-sk',
    databaseURL: 'https://kazipur-shop-sk-default-rtdb.firebaseio.com',
    storageBucket: 'kazipur-shop-sk.firebasestorage.app',
    androidClientId: '311227783889-lid89qeev3ctshn11duemuoplht2v0qj.apps.googleusercontent.com',
    iosClientId: '311227783889-8i0vo8hf4rm3sjrbnv9bcgr4cu2g8bvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
